volumes:
  npm_data:
    name: nginx-proxy-manager-data
  npm_ssl_certificates:
    name: nginx-proxy-manager-ssl
    
networks:
  nginx-proxy-manager-network:
    external: true

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager-prod
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      # より分かりやすいディレクトリ名
      - ./nginx-proxy-manager-data:/data
      - ./nginx-proxy-manager-ssl:/etc/letsencrypt
    networks:
      - nginx-proxy-manager-network